name = "konma/karbon-emission"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken Smart Contract for CET"

[repository]
user = "KonmaORG"
project = "Karbon-Emission"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.2.0"
source = "github"

