name = "konma/karbon-emission"
version = "0.0.0"
compiler = "v1.1.11"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken Smart Contract for CET"

[repository]
user = "KonmaORG"
project = "Karbon-Emission"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.2.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "2.1.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.11"
source = "github"

[[dependencies]]
name = "aiken-extra/tx_util"
version = "1.215.202411"
source = "github"

[[dependencies]]
name = "logical-mechanism/assist"
version = "v0.5.1"
source = "github"
